import Head from 'next/head'
import styles from '@/styles/Home.module.css'

export default function Profile() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <h1>user profile</h1>
      </main>
    </>
  )
}
